- name: Packages are present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - cd-paranoia
    - cdrdao
    - libiso9660-dev
    - libgirepository1.0-dev
    - libsndfile1-dev
    - flac
    - sox
    - swig
    - git
    - libcairo2-dev
    - libdiscid-dev
    - build-essential
    - python3
    - python3-pip


- name: Virtualenv is installed with pip
  ansible.builtin.pip:
    name: virtualenv
